name: Linux Build and Deploy
on:
  workflow_dispatch:
   inputs:
      environment:
        type: choice
        description: Environment
        options:
         - "development"

jobs:
  build-artifact:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-1"

      - name: Packer Init
        run: packer init .

      - name: Packer Build - Branches
        if: startsWith(github.ref, 'refs/heads/')
        run: packer build aws-ubuntu.pkr.hcl

  
